name: cefcfco_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^3.0.3
  flutter_redux: ^0.5.3
  event_bus: ^1.0.3
  connectivity: ^0.4.2
  cupertino_icons: ^0.1.2
  dio: ^2.0.10
  flutter_jpush: ^0.0.4
  shared_preferences: ^0.5.1+1
  fluro: "^1.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
  - assets/login_logo.png
  - assets/user.jpg

  fonts:
  - family: WorkSansSemiBold
    fonts:
    - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

  - family: WorkSansBold
    fonts:
    - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

  - family: WorkSansMedium
    fonts:
    - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
